# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6946df1f35558ebaf5482cba777fabc36884910a7febd2062b9acfd34df38eeab4d4c8f583733cba14d4560c386b657799211a9bab00684b1091e10618b53f0

test:
  secret_key_base: db9a56b8448c2398d4276eb13781b8444dc7d5f4d41bacb65e9ded1599c1ab35467dd2d9be4e6b4a66e1c9cd418215d73bf9d21bbc7aea9ec721fc3ac9b551f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
